// Code generated by coz. DO NOT EDIT.
/**
 * Repeatable of the-component
 * @module the-repeatable
 * @version 1.0.8
 */
'use strict'

import TheRepeatable from './TheRepeatable'
import TheRepeatableStyle from './TheRepeatableStyle'

export default TheRepeatable

export {
  TheRepeatable,
  TheRepeatableStyle
}
